"""THE test that makes the port trustworthy: data/parity.json was generated BY the
web app's TypeScript implementation (npx tsx scripts/export-plugin-data.ts) — the
numpy port must reproduce its numbers on the same RGBA bytes.

Tolerances: float64 math is identical op-for-op, but `pow` may differ by ~1 ULP
between V8 and libm, which can flip a histogram-bin membership on a pixel sitting
exactly at a boundary. Percentile values are therefore allowed one bin (1/1024) of
slack; everything else must agree to 1e-6 (means/sums) or exactly (ints, CCT-50s,
None-ness)."""

from __future__ import annotations

import base64
import json
import math
from pathlib import Path

import numpy as np
import pytest

from lightmatch_max.core.metrics import (
    diff_vectors,
    match_percent,
    measure_from_pixels,
    scene_evidence,
    score_vectors,
    wb_exposure_evidence,
)

PARITY = json.loads((Path(__file__).parent.parent / "data" / "parity.json").read_text("utf-8"))
BIN = 1 / 1024
EPS = 1e-6


def measure_case(case: dict) -> dict:
    raw = np.frombuffer(base64.b64decode(case["rgba_b64"]), dtype=np.uint8)
    return measure_from_pixels(raw, case["w"], case["h"])


def assert_close(py, ts, path=""):
    if ts is None or py is None:
        assert py == ts, f"{path}: {py!r} != {ts!r}"
        return
    if isinstance(ts, bool) or isinstance(py, bool):
        assert py == ts, f"{path}: {py!r} != {ts!r}"
        return
    if isinstance(ts, (int, float)):
        assert isinstance(py, (int, float)), f"{path}: type {type(py)}"
        tol = BIN + EPS if any(k in path for k in ("lum.p", "sat.p95", "contrast", "grad", "p5", "p50", "p95")) else EPS
        # contrast values are differences of bin centers → up to 2 bins of slack
        if "contrast" in path or "midSlope" in path:
            tol = 2 * BIN / 0.5 + EPS
        assert math.isfinite(float(py)) == math.isfinite(float(ts)), path
        assert abs(float(py) - float(ts)) <= tol, f"{path}: {py} vs {ts} (tol {tol})"
        return
    if isinstance(ts, dict):
        assert set(py.keys()) == set(ts.keys()), f"{path}: keys {sorted(py.keys())} != {sorted(ts.keys())}"
        for k in ts:
            assert_close(py[k], ts[k], f"{path}.{k}")
        return
    if isinstance(ts, list):
        assert len(py) == len(ts), f"{path}: len"
        for i, (a, b) in enumerate(zip(py, ts)):
            assert_close(a, b, f"{path}[{i}]")
        return
    assert py == ts, f"{path}: {py!r} != {ts!r}"


@pytest.mark.parametrize("case", PARITY["cases"], ids=[c["name"] for c in PARITY["cases"]])
def test_metrics_parity(case):
    assert_close(measure_case(case), case["metrics"], case["name"])


@pytest.mark.parametrize("pair", PARITY["pairs"], ids=[f"{p['ref']}__vs__{p['cur']}" for p in PARITY["pairs"]])
def test_pair_parity(pair):
    by_name = {c["name"]: c for c in PARITY["cases"]}
    a = measure_case(by_name[pair["ref"]])
    b = measure_case(by_name[pair["cur"]])
    assert_close(diff_vectors(b, a), pair["diff"], "diff")
    score = score_vectors(a, b)
    assert abs(score - pair["score"]) <= 0.05, f"score {score} vs {pair['score']}"
    assert match_percent(score) == pair["match_percent"]
    assert_close(wb_exposure_evidence(a, b), pair["wb_exposure"], "wb_exposure")
    assert_close(scene_evidence(a, b), pair["scene"], "scene")


def test_identical_pair_is_a_perfect_match():
    c = PARITY["cases"][0]
    m = measure_case(c)
    assert score_vectors(m, m) == 0
    assert match_percent(0) == 100
