"""Loaders for the exported "brain" — packs / prompts / knownprops JSON generated by
the web repo's `npx tsx scripts/export-plugin-data.ts` (the canonical TS source).
Nothing in this repo hand-copies prompt prose or pack vocabulary: regenerate the
data/ artifacts to re-sync the plugin with the web app."""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"


@lru_cache(maxsize=None)
def _load(name: str) -> Any:
    with open(DATA_DIR / name, "r", encoding="utf-8") as f:
        return json.load(f)


def packs() -> dict:
    return _load("packs.json")


def prompts() -> dict:
    return _load("prompts.json")


def knownprops() -> dict:
    return _load("knownprops.json")


# -- pack surface ---------------------------------------------------------------------
def target_label(target: str) -> str:
    return packs().get(target, {}).get("label", target)


def sheet(target: str) -> list[dict]:
    return packs().get(target, {}).get("sheet", [])


@lru_cache(maxsize=None)
def _entry_index(target: str) -> dict[str, dict]:
    idx: dict[str, dict] = {}
    for group in sheet(target):
        for e in group.get("entries", []):
            idx[e["id"]] = e
    return idx


def lookup(target: str, param_id: str) -> Optional[dict]:
    return _entry_index(target).get(param_id)


def clamp(target: str, param_id: str, value: Any) -> tuple[Any, bool]:
    """Numeric clamp into the pack range — (value, clamped_flag). Non-numeric values
    and unknown params pass through unclamped (validation handles unknowns)."""
    e = lookup(target, param_id)
    if not e or not isinstance(value, (int, float)):
        return value, False
    rng = e.get("range")
    if not (isinstance(rng, list) and len(rng) == 2):
        return value, False
    lo, hi = rng
    if not (isinstance(lo, (int, float)) and isinstance(hi, (int, float)) and lo < hi):
        return value, False
    if value < lo:
        return lo, True
    if value > hi:
        return hi, True
    return value, False


def system_prompt(target: str, mode: str, lock_globals: bool = False) -> str:
    key = f"{target}.{mode}.{'locked' if lock_globals else 'free'}"
    sys = prompts()["system"].get(key)
    if not sys:
        raise KeyError(f"no exported system prompt for {key} — regenerate data/ from the web repo")
    return sys


def evidence_legend() -> str:
    return prompts()["legend"]


def emit_schema(mode: str) -> dict:
    return prompts()["emit_correction_schema" if mode == "correction" else "emit_recipe_schema"]
