"""LightMatch photometry — a faithful numpy port of the web app's measurement core
(web/src/lib/metrics.ts). Every constant, weight, and formula mirrors the TS source;
data/parity.json (generated BY that TS implementation) proves the two produce the
same numbers — see tests/test_parity.py. If you change anything here, regenerate the
parity vectors from the web repo and make the suite green again.

The measured shape (a "MetricVector") is a plain dict matching the TS JSON exactly,
so sessions and evidence blocks are interchangeable between the web app and the
plugin.
"""

from __future__ import annotations

import math
from typing import Any, Optional

import numpy as np

# -- constants (mirror metrics.ts verbatim) -----------------------------------------
HIST_BINS = 1024
CLIP_HI_THRESH = 250  # sRGB 0..255: pixel counts toward clip.hi when max(r,g,b) >= this
CLIP_LO_THRESH = 5    # ... clip.lo when max(r,g,b) <= this
SKY_TOP_FRAC = 0.45
SKY_MIN_FRAC = 0.04
SKY_MIN_DIM_FRAC = 0.1
GRID_CELL_MIN_COVERAGE = 0.01
GRAD_MID_LO = 0.08
GRAD_MID_HI = 0.7
GRAD_CLAMP = 0.5
GRAD_MIN_PIXELS = 100
ALPHA_MIN = 16

MATCH_THRESHOLD = 3  # look-distance <= this ⇒ "lighting matched"

SCORE_WEIGHTS: dict[str, float] = {
    "lum.p5": 3, "lum.p50": 3, "lum.p95": 3,
    "lum.p25": 2, "lum.p75": 2, "lum.mean": 2,
    "contrast.spread": 2, "contrast.midSlope": 2,
    "wb.warmthShadow": 2, "wb.warmthHighlight": 2, "wb.tint": 2,
    "clip.hi": 1.5, "clip.lo": 1.5,
    "sat.mean": 1,
    **{f"grid.{i}": 0.5 for i in range(16)},
}


def js_round(v: float, digits: int = 0) -> float:
    """JS Math.round semantics (half toward +infinity), scaled — Python's round()
    is banker's rounding and would drift from the TS output on exact halves."""
    if not math.isfinite(v):
        return v  # math.floor(nan/inf) raises ValueError — a non-finite input can only
                  # come from a corrupted metric vector; pass it through, don't explode
    f = 10.0 ** digits
    return math.floor(v * f + 0.5) / f


def match_percent(score: float) -> int:
    return int(max(0, min(100, js_round(100 - score))))


# -- linearize / luminance (vectorized) ----------------------------------------------
def linearize(c: np.ndarray) -> np.ndarray:
    """sRGB 0..1 → linear 0..1 (per-channel), elementwise."""
    c = np.asarray(c, dtype=np.float64)
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)


def luminance(r: np.ndarray, g: np.ndarray, b: np.ndarray) -> np.ndarray:
    return 0.2126 * linearize(r) + 0.7152 * linearize(g) + 0.0722 * linearize(b)


# -- fixed-bin histogram percentiles (bin indices / bin-center values) ---------------
def percentile_bins_from_histogram(values: np.ndarray, ps: list[float], n_bins: int = HIST_BINS) -> list[int]:
    values = np.asarray(values, dtype=np.float64)
    n = values.size
    idx = np.clip(np.floor(values * n_bins).astype(np.int64), 0, n_bins - 1)
    hist = np.bincount(idx, minlength=n_bins)
    cum = np.cumsum(hist)
    out: list[int] = []
    for p in ps:
        target = (p / 100.0) * n
        # first bin whose cumulative count >= target (TS scans with `cum >= target`)
        b = int(np.searchsorted(cum, target, side="left"))
        out.append(min(b, n_bins - 1))
    return out


def percentiles_from_histogram(values: np.ndarray, ps: list[float], n_bins: int = HIST_BINS) -> list[float]:
    return [(b + 0.5) / n_bins for b in percentile_bins_from_histogram(values, ps, n_bins)]


# -- core measurement from a raw RGBA buffer -----------------------------------------
def measure_from_pixels(data: np.ndarray, w: int, h: int) -> dict[str, Any]:
    """data: uint8 array, flat length w*h*4 or shape (h, w, 4), RGBA row-major.
    Returns the MetricVector dict (same shape/keys as the TS implementation)."""
    if w <= 0 or h <= 0:
        raise ValueError("empty image (w/h <= 0)")  # else stat_n=0 -> ZeroDivisionError
    px = np.asarray(data, dtype=np.uint8).reshape(h, w, 4)
    n = w * h

    r255 = px[..., 0].astype(np.float64).ravel()
    g255 = px[..., 1].astype(np.float64).ravel()
    b255 = px[..., 2].astype(np.float64).ravel()
    a255 = px[..., 3].ravel()

    opaque = a255 >= ALPHA_MIN
    opaque_count = int(opaque.sum())
    all_transparent = opaque_count == 0
    counted = np.ones(n, dtype=bool) if all_transparent else opaque
    stat_n = n if all_transparent else opaque_count

    r = r255 / 255.0
    g = g255 / 255.0
    b = b255 / 255.0
    lin_r = linearize(r)
    lin_g = linearize(g)
    lin_b = linearize(b)
    lum = 0.2126 * lin_r + 0.7152 * lin_g + 0.0722 * lin_b

    maxc255 = np.maximum(np.maximum(r255, g255), b255)
    is_hi = maxc255 >= CLIP_HI_THRESH
    is_lo = maxc255 <= CLIP_LO_THRESH

    mx = np.maximum(np.maximum(r, g), b)
    mn = np.minimum(np.minimum(r, g), b)
    with np.errstate(divide="ignore", invalid="ignore"):
        sat_arr = np.where(mx == 0, 0.0, (mx - mn) / np.where(mx == 0, 1.0, mx))

    clip_hi = float(is_hi[counted].sum()) / stat_n
    clip_lo = float(is_lo[counted].sum()) / stat_n
    sat_sum = float(sat_arr[counted].sum())
    mean_lin_r = float(lin_r[counted].sum()) / stat_n
    mean_lin_g = float(lin_g[counted].sum()) / stat_n
    mean_lin_b = float(lin_b[counted].sum()) / stat_n

    lum_for_pct = lum[counted]
    sat_for_pct = sat_arr[counted]

    p1, p5, p25, p50, p75, p95, p99 = percentiles_from_histogram(lum_for_pct, [1, 5, 25, 50, 75, 95, 99])
    p25_bin, p60_bin, p75_bin = percentile_bins_from_histogram(lum_for_pct, [25, 60, 75])
    lum_mean = float(lum[counted].sum()) / stat_n

    contrast = {"spread": p95 - p5, "midSlope": (p75 - p25) / 0.5}

    # -- white balance split + the sky flatness counter (dimN), exactly as the TS pass
    bin_idx = np.clip(np.floor(lum * HIST_BINS).astype(np.int64), 0, HIST_BINS - 1)
    c_bin = bin_idx[counted]
    dim_n = int((c_bin < p60_bin).sum())

    sh_mask = c_bin <= p25_bin
    hi_mask = c_bin >= p75_bin
    c_lin_r = lin_r[counted]
    c_lin_g = lin_g[counted]
    c_lin_b = lin_b[counted]
    sh_n = int(sh_mask.sum())
    hi_n = int(hi_mask.sum())
    shadow = {
        "r": float(c_lin_r[sh_mask].sum()) / sh_n if sh_n else 0.0,
        "g": float(c_lin_g[sh_mask].sum()) / sh_n if sh_n else 0.0,
        "b": float(c_lin_b[sh_mask].sum()) / sh_n if sh_n else 0.0,
    }
    highlight = {
        "r": float(c_lin_r[hi_mask].sum()) / hi_n if hi_n else 0.0,
        "g": float(c_lin_g[hi_mask].sum()) / hi_n if hi_n else 0.0,
        "b": float(c_lin_b[hi_mask].sum()) / hi_n if hi_n else 0.0,
    }
    warmth_shadow = (shadow["r"] - shadow["b"]) / (shadow["r"] + shadow["b"] + 1e-9)
    warmth_highlight = (highlight["r"] - highlight["b"]) / (highlight["r"] + highlight["b"] + 1e-9)
    tint = mean_lin_g - (mean_lin_r + mean_lin_b) / 2

    sat_mean = sat_sum / stat_n
    (sat_p95,) = percentiles_from_histogram(sat_for_pct, [95])

    # -- 4x4 grid with coverage-gated neutral (stress fix C11 mirrored) ---------------
    ys, xs = np.divmod(np.arange(n), w)
    gy = np.minimum((ys * 4) // h, 3)
    gx = np.minimum((xs * 4) // w, 3)
    cell = (gy * 4 + gx).astype(np.int64)
    grid_total = np.bincount(cell, minlength=16).astype(np.float64)
    grid_count = np.bincount(cell[counted], minlength=16).astype(np.float64)
    grid_sum = np.bincount(cell[counted], weights=lum[counted], minlength=16)
    grid: list[float] = []
    for i in range(16):
        covered = grid_count[i] > 0 and grid_count[i] >= grid_total[i] * GRID_CELL_MIN_COVERAGE
        grid.append(float(grid_sum[i] / grid_count[i]) if covered else lum_mean)

    # -- optional sky region (top rows, bright-for-this-image, flatness-guarded) ------
    sky_rows = ys < (h * SKY_TOP_FRAC)
    sky_mask = sky_rows & counted & (bin_idx >= p60_bin)
    sky_n = int(sky_mask.sum())
    sky: Optional[dict[str, float]] = None
    if sky_n:
        sky_frac = sky_n / stat_n
        dim_frac = dim_n / stat_n
        if sky_frac >= SKY_MIN_FRAC and dim_frac >= SKY_MIN_DIM_FRAC:
            sky = {
                "frac": sky_frac,
                "meanLum": float(lum[sky_mask].sum()) / sky_n,
                "r": float(lin_r[sky_mask].sum()) / sky_n,
                "g": float(lin_g[sky_mask].sum()) / sky_n,
                "b": float(lin_b[sky_mask].sum()) / sky_n,
            }

    # -- optional edge-softness gradient distribution (mid-tone |dL|) -----------------
    grad: Optional[dict[str, float]] = None
    if w >= 3 and h >= 3:
        lum2 = lum.reshape(h, w)
        center = lum2[1:-1, 1:-1]
        dx = (lum2[1:-1, 2:] - lum2[1:-1, :-2]) / 2
        dy = (lum2[2:, 1:-1] - lum2[:-2, 1:-1]) / 2
        mag = np.sqrt(dx * dx + dy * dy)
        band = (center >= GRAD_MID_LO) & (center <= GRAD_MID_HI)
        if not all_transparent:
            op2 = opaque.reshape(h, w)
            band &= op2[1:-1, 1:-1] & op2[1:-1, 2:] & op2[1:-1, :-2] & op2[2:, 1:-1] & op2[:-2, 1:-1]
        vals = np.minimum(mag[band], GRAD_CLAMP) / GRAD_CLAMP
        if vals.size >= GRAD_MIN_PIXELS:
            g50, g90 = percentiles_from_histogram(vals, [50, 90])
            grad = {"p50": g50, "p90": g90}

    out: dict[str, Any] = {
        "lum": {"p1": p1, "p5": p5, "p25": p25, "p50": p50, "p75": p75, "p95": p95, "p99": p99, "mean": lum_mean},
        "clip": {"hi": clip_hi, "lo": clip_lo},
        "contrast": contrast,
        "wb": {"shadow": shadow, "highlight": highlight, "warmthShadow": warmth_shadow, "warmthHighlight": warmth_highlight, "tint": tint},
        "sat": {"mean": sat_mean, "p95": sat_p95},
        "grid": grid,
    }
    if sky is not None:
        out["sky"] = sky
    if grad is not None:
        out["grad"] = grad
    return out


# -- diff / score --------------------------------------------------------------------
_SCALAR_DIFF_KEYS = [
    ("lum.p1", ("lum", "p1")), ("lum.p5", ("lum", "p5")), ("lum.p25", ("lum", "p25")),
    ("lum.p50", ("lum", "p50")), ("lum.p75", ("lum", "p75")), ("lum.p95", ("lum", "p95")),
    ("lum.p99", ("lum", "p99")), ("lum.mean", ("lum", "mean")),
    ("clip.hi", ("clip", "hi")), ("clip.lo", ("clip", "lo")),
    ("contrast.spread", ("contrast", "spread")), ("contrast.midSlope", ("contrast", "midSlope")),
    ("wb.warmthShadow", ("wb", "warmthShadow")), ("wb.warmthHighlight", ("wb", "warmthHighlight")),
    ("wb.tint", ("wb", "tint")),
    ("sat.mean", ("sat", "mean")), ("sat.p95", ("sat", "p95")),
]


def diff_vectors(a: dict, b: dict) -> dict[str, float]:
    """(b − a) per scalar plus grid.0..15 — identical key set to the TS diff."""
    out: dict[str, float] = {}
    for key, (k1, k2) in _SCALAR_DIFF_KEYS:
        out[key] = b[k1][k2] - a[k1][k2]
    for i in range(16):
        out[f"grid.{i}"] = b["grid"][i] - a["grid"][i]
    return out


def score_vectors(ref_m: dict, attempt_m: dict) -> float:
    d = diff_vectors(ref_m, attempt_m)
    wsum = 0.0
    wdsum = 0.0
    for key, wgt in SCORE_WEIGHTS.items():
        di = d.get(key, 0.0) or 0.0
        wsum += wgt
        wdsum += wgt * di * di
    raw = (100.0 * math.sqrt(wdsum / wsum)) / 0.35
    return min(100.0, raw)


# -- WB / exposure evidence -----------------------------------------------------------
def cct_from_linear_rgb(r: float, g: float, b: float) -> Optional[int]:
    if not all(math.isfinite(v) for v in (r, g, b)):
        return None
    if r < 0 or g < 0 or b < 0:
        return None
    X = 0.4124 * r + 0.3576 * g + 0.1805 * b
    Y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    Z = 0.0193 * r + 0.1192 * g + 0.9505 * b
    s = X + Y + Z
    if s < 1e-9:
        return None
    x = X / s
    y = Y / s
    denom = 0.1858 - y
    if abs(denom) < 1e-6:
        return None
    nn = (x - 0.332) / denom
    cct = 449 * nn**3 + 3525 * nn**2 + 6823.3 * nn + 5520.33
    if not math.isfinite(cct):
        return None
    clamped = min(25000.0, max(1000.0, cct))
    return int(js_round(clamped / 50) * 50)


def tint_gm_from_linear_rgb(r: float, g: float, b: float) -> Optional[float]:
    if not all(math.isfinite(v) for v in (r, g, b)):
        return None
    if r < 0 or g < 0 or b < 0:
        return None
    s = r + g + b
    if s < 1e-9:
        return None
    return js_round((g - (r + b) / 2) / s, 4)


def wb_exposure_evidence(ref_m: dict, cur_m: dict) -> dict[str, Any]:
    signal_min = 1 / HIST_BINS
    ev = None
    if ref_m["lum"]["p50"] > signal_min and cur_m["lum"]["p50"] > signal_min:
        ev = js_round(math.log2(ref_m["lum"]["p50"] / cur_m["lum"]["p50"]), 2)
    def cct(side: dict) -> Optional[int]:
        return cct_from_linear_rgb(side["r"], side["g"], side["b"])
    def tint(side: dict) -> Optional[float]:
        return tint_gm_from_linear_rgb(side["r"], side["g"], side["b"])
    return {
        "wb_estimate_k": {
            "reference_highlights": cct(ref_m["wb"]["highlight"]),
            "current_highlights": cct(cur_m["wb"]["highlight"]),
            "reference_shadows": cct(ref_m["wb"]["shadow"]),
            "current_shadows": cct(cur_m["wb"]["shadow"]),
        },
        "tint_gm": {
            "reference_highlights": tint(ref_m["wb"]["highlight"]),
            "current_highlights": tint(cur_m["wb"]["highlight"]),
            "reference_shadows": tint(ref_m["wb"]["shadow"]),
            "current_shadows": tint(cur_m["wb"]["shadow"]),
        },
        "exposure_gap_ev": ev,
    }


# -- scene evidence -------------------------------------------------------------------
_CELL_CENTERS = [-0.75, -0.25, 0.25, 0.75]


def _grid_centroid(grid: list[float]) -> Optional[dict[str, float]]:
    total = sx = sy = 0.0
    for r_ in range(4):
        for c_ in range(4):
            v = grid[r_ * 4 + c_]
            total += v
            sx += _CELL_CENTERS[c_] * v
            sy += _CELL_CENTERS[r_] * v
    if total < 1e-6:
        return None
    return {"x": js_round(sx / total, 3), "y": js_round(sy / total, 3)}


def _grid_key_fill_ratio(grid: list[float]) -> Optional[float]:
    s = sorted(grid, reverse=True)
    key = (s[0] + s[1] + s[2] + s[3]) / 4
    fill = (s[12] + s[13] + s[14] + s[15]) / 4
    if key < 1e-6:
        return None
    if fill < 1e-6:
        return 99.0
    return min(99.0, js_round(key / fill, 2))


def _anchors_of(m: dict) -> dict[str, float]:
    r4 = lambda v: js_round(v, 4)  # noqa: E731
    return {
        "p5": r4(m["lum"]["p5"]), "p50": r4(m["lum"]["p50"]), "p95": r4(m["lum"]["p95"]),
        "clip_hi": r4(m["clip"]["hi"]), "clip_lo": r4(m["clip"]["lo"]), "sat": r4(m["sat"]["mean"]),
    }


def _sky_estimate_of(m: dict) -> Optional[dict[str, Any]]:
    sky = m.get("sky")
    if not sky or not math.isfinite(sky.get("frac", float("nan"))) or sky["frac"] < SKY_MIN_FRAC:
        return None
    return {
        "frac": js_round(sky["frac"], 4),
        "mean_lum": js_round(sky["meanLum"], 4),
        "cct_k": cct_from_linear_rgb(sky["r"], sky["g"], sky["b"]),
        "tint_gm": tint_gm_from_linear_rgb(sky["r"], sky["g"], sky["b"]),
    }


def _edge_softness_of(m: dict) -> Optional[float]:
    g = m.get("grad")
    if not g or not math.isfinite(g.get("p90", float("nan"))):
        return None
    return js_round(g["p90"], 4)


def scene_evidence(ref_m: dict, cur_m: dict) -> dict[str, Any]:
    return {
        "light_centroid": {"reference": _grid_centroid(ref_m["grid"]), "current": _grid_centroid(cur_m["grid"])},
        "key_fill_ratio": {"reference": _grid_key_fill_ratio(ref_m["grid"]), "current": _grid_key_fill_ratio(cur_m["grid"])},
        "anchors": {"reference": _anchors_of(ref_m), "current": _anchors_of(cur_m)},
        "sky_estimate": {"reference": _sky_estimate_of(ref_m), "current": _sky_estimate_of(cur_m)},
        "edge_softness": {"reference": _edge_softness_of(ref_m), "current": _edge_softness_of(cur_m)},
    }


# -- image ingestion (PIL) ------------------------------------------------------------
def downscale_dimensions(sw: int, sh: int, max_edge: int) -> tuple[int, int, float]:
    long_edge = max(sw, sh)
    scale = max_edge / long_edge if long_edge > max_edge else 1.0
    return max(1, int(js_round(sw * scale))), max(1, int(js_round(sh * scale))), scale


def measure_image(img) -> dict[str, Any]:
    """PIL.Image → MetricVector: thumb to 256 long-edge (same rule as the web's
    measure()) then measure_from_pixels. Resampling differs slightly from a browser
    canvas (PIL bilinear vs. canvas drawImage), so cross-app scores are near- but not
    bit-identical; WITHIN the plugin everything is deterministic."""
    from PIL import Image
    rgba = img.convert("RGBA")
    w, h, _ = downscale_dimensions(rgba.width, rgba.height, 256)
    if (w, h) != (rgba.width, rgba.height):
        rgba = rgba.resize((w, h), Image.BILINEAR)
    return measure_from_pixels(np.asarray(rgba, dtype=np.uint8), rgba.width, rgba.height)
